language: csharp
solution: CSharpOptParser.sln
mono:
  - latest
  - 3.12.0
  - 3.10.0
install:
  - nuget restore CSharpOptParser.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CSharpOptParser.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./CSharpOptParser.Tests/bin/Release/CSharpOptParser.Tests.dll