version: 1.0.{build}-beta

install:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

init:
  - git config --global core.autocrlf true

environment:
  COVERALLS_REPO_TOKEN:
    secure: idd8FrugagXuNN2Bs5oo8wRrz5MYhKTGbzx99g7wTihu7w4D6ZfXqL8dcTFBkdIP

build:
  project: CSharpOptParser.sln

after_test: 
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[CSharpOptParser*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  CSharpOptParser.Tests\bin\debug\CSharpOptParser.Tests.dll" -output:coverage.xml
    - packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover coverage.xml